"""Tests for core.media — probing, extraction/cutting, WAV I/O.

Uses only the committed fixtures under tests/fixtures/ (generated by
scripts/make_fixtures.py) plus files created in tmp_path.
"""

import shutil
from pathlib import Path

import numpy as np
import pytest
import soundfile as sf

from heli_noise.core.exceptions import InvalidTimeRangeError, MediaDecodeError
from heli_noise.core.media import (
    MediaInfo,
    _parse_audio_stream,
    extract_audio,
    load_wav,
    probe_media,
    save_wav,
)

FIXTURES = Path(__file__).parent / "fixtures"
TONE_WAV = FIXTURES / "tone_440hz_48k.wav"
TONE_MP4 = FIXTURES / "tone_440hz_48k.mp4"
TONE_MP3 = FIXTURES / "tone_440hz_48k.mp3"
MIX_WAV = FIXTURES / "mix_100_400_1000hz_44k1.wav"


def _dominant_frequency(samples: np.ndarray, sample_rate: int) -> float:
    """Return the frequency of the largest FFT magnitude peak."""
    spectrum = np.abs(np.fft.rfft(samples))
    freqs = np.fft.rfftfreq(len(samples), d=1.0 / sample_rate)
    return float(freqs[np.argmax(spectrum)])


class TestParseAudioStream:
    """Real-world ffmpeg stderr shapes, parsed without running ffmpeg."""

    @pytest.mark.parametrize(
        ("line", "expected"),
        [
            ("Stream #0:1(und): Audio: aac (LC), 48000 Hz, stereo, fltp", (48_000, 2)),
            ("Stream #0:0: Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s", (48_000, 1)),
            ("Stream #0:1: Audio: aac (LC), 48000 Hz, 5.1(side), fltp", (48_000, 6)),
            ("Stream #0:1: Audio: aac, 48000 Hz, 5.1, fltp", (48_000, 6)),
            ("Stream #0:1: Audio: pcm_s16le, 48000 Hz, 4.0, s16", (48_000, 4)),
            ("Stream #0:1: Audio: aac, 44100 Hz, 7.1(wide), fltp", (44_100, 8)),
            ("Stream #0:1: Audio: pcm_s16le, 48000 Hz, quad, s16", (48_000, 4)),
            ("Stream #0:1: Audio: pcm_s16le, 44100 Hz, 2 channels, s16", (44_100, 2)),
            ("Stream #0:1: Audio: ambisonic, 48000 Hz, weird_layout, fltp", (48_000, 2)),
        ],
    )
    def test_layouts(self, line: str, expected: tuple[int, int]) -> None:
        assert _parse_audio_stream(line) == expected

    def test_no_audio_stream_returns_none(self) -> None:
        assert _parse_audio_stream("Stream #0:0: Video: h264, yuv420p, 1920x1080") is None


class TestProbeMedia:
    def test_wav(self) -> None:
        info = probe_media(TONE_WAV)
        assert isinstance(info, MediaInfo)
        assert info.duration == pytest.approx(1.0, abs=0.05)
        assert info.sample_rate == 48_000
        assert info.channels == 1

    def test_mp4(self) -> None:
        info = probe_media(TONE_MP4)
        assert info.duration == pytest.approx(1.0, abs=0.1)
        assert info.sample_rate == 48_000
        assert info.channels == 1

    def test_mp3(self) -> None:
        info = probe_media(TONE_MP3)
        assert info.duration == pytest.approx(1.0, abs=0.1)
        assert info.sample_rate == 48_000

    def test_44k1_wav(self) -> None:
        info = probe_media(MIX_WAV)
        assert info.duration == pytest.approx(1.5, abs=0.05)
        assert info.sample_rate == 44_100

    def test_missing_file(self, tmp_path: Path) -> None:
        with pytest.raises(MediaDecodeError, match="not found"):
            probe_media(tmp_path / "does_not_exist.mp4")

    def test_no_audio_stream(self, tmp_path: Path) -> None:
        garbage = tmp_path / "not_media.mp4"
        garbage.write_bytes(b"this is not a media file at all" * 10)
        with pytest.raises(MediaDecodeError):
            probe_media(garbage)


class TestExtractAudio:
    def test_cut_from_mp4(self, tmp_path: Path) -> None:
        out = tmp_path / "cut.wav"
        result = extract_audio(TONE_MP4, 0.2, 0.7, out)
        assert result == out
        info = sf.info(str(out))
        assert info.channels == 1
        assert info.subtype == "PCM_16"
        assert info.samplerate == 48_000
        assert info.frames == pytest.approx(0.5 * 48_000, rel=0.05)

    def test_cut_from_wav(self, tmp_path: Path) -> None:
        out = tmp_path / "cut.wav"
        extract_audio(TONE_WAV, 0.1, 0.9, out)
        info = sf.info(str(out))
        assert info.frames == pytest.approx(0.8 * 48_000, rel=0.05)
        assert info.samplerate == 48_000

    def test_extracted_content_is_the_tone(self, tmp_path: Path) -> None:
        out = tmp_path / "cut.wav"
        extract_audio(TONE_MP4, 0.2, 0.7, out)
        samples, sample_rate = load_wav(out)
        assert _dominant_frequency(samples, sample_rate) == pytest.approx(440.0, abs=5.0)

    def test_original_sample_rate_preserved(self, tmp_path: Path) -> None:
        out = tmp_path / "cut.wav"
        extract_audio(MIX_WAV, 0.0, 1.0, out)
        assert sf.info(str(out)).samplerate == 44_100

    def test_windows_critical_path_spaces_and_non_ascii(self, tmp_path: Path) -> None:
        folder = tmp_path / "Hüseyin Yeni Klasör"
        folder.mkdir()
        source = folder / "uçuş kaydı 1.mp4"
        shutil.copy(TONE_MP4, source)
        out = folder / "uçuş kaydı 1 çıktı.wav"
        extract_audio(source, 0.2, 0.7, out)
        samples, sample_rate = load_wav(out)
        assert _dominant_frequency(samples, sample_rate) == pytest.approx(440.0, abs=5.0)

    @pytest.mark.parametrize(
        ("start", "stop"),
        [(-0.1, 0.5), (0.5, 0.5), (0.7, 0.2), (0.0, 5.0)],
    )
    def test_invalid_ranges(self, tmp_path: Path, start: float, stop: float) -> None:
        with pytest.raises(InvalidTimeRangeError):
            extract_audio(TONE_WAV, start, stop, tmp_path / "out.wav")

    def test_missing_input(self, tmp_path: Path) -> None:
        with pytest.raises(MediaDecodeError):
            extract_audio(tmp_path / "missing.mp4", 0.0, 1.0, tmp_path / "out.wav")


class TestWavIO:
    def test_load_mono(self) -> None:
        samples, sample_rate = load_wav(TONE_WAV)
        assert samples.ndim == 1
        assert sample_rate == 48_000
        assert samples.dtype == np.float64
        assert np.max(np.abs(samples)) <= 1.0

    def test_load_stereo_downmixes_by_averaging(self, tmp_path: Path) -> None:
        sample_rate = 48_000
        left = np.full(sample_rate // 10, 0.5)
        right = np.full(sample_rate // 10, -0.1)
        stereo_path = tmp_path / "stereo.wav"
        sf.write(str(stereo_path), np.column_stack([left, right]), sample_rate)
        samples, _ = load_wav(stereo_path)
        assert samples.ndim == 1
        assert np.allclose(samples, 0.2, atol=1e-3)  # (0.5 + -0.1) / 2

    def test_load_invalid_file(self, tmp_path: Path) -> None:
        bad = tmp_path / "bad.wav"
        bad.write_bytes(b"RIFFgarbage")
        with pytest.raises(MediaDecodeError):
            load_wav(bad)

    def test_save_roundtrip(self, tmp_path: Path) -> None:
        sample_rate = 44_100
        t = np.arange(sample_rate // 2) / sample_rate
        signal = 0.8 * np.sin(2 * np.pi * 100.0 * t)
        out = tmp_path / "sub" / "saved.wav"  # parent dir auto-created
        save_wav(out, signal, sample_rate)
        info = sf.info(str(out))
        assert info.channels == 1
        assert info.subtype == "PCM_16"
        assert info.samplerate == sample_rate
        reloaded, reloaded_rate = load_wav(out)
        assert reloaded_rate == sample_rate
        assert np.allclose(reloaded, signal, atol=1e-3)

    def test_save_clips_out_of_range(self, tmp_path: Path) -> None:
        out = tmp_path / "clipped.wav"
        save_wav(out, np.array([2.0, -3.0, 0.5]), 48_000)
        reloaded, _ = load_wav(out)
        assert np.max(np.abs(reloaded)) <= 1.0
        assert reloaded[2] == pytest.approx(0.5, abs=1e-3)
